/**
 * Extract Version — Codegen script for Docora
 *
 * Reads milestone from .planning/STATE.md (single source of truth),
 * generates src/version.ts with baked values, syncs package.json,
 * and prints the version string to stdout for CI consumption.
 *
 * Usage: node scripts/extract-version.cjs
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const STATE_PATH = path.join(ROOT, ".planning", "STATE.md");
const VERSION_TS_PATH = path.join(ROOT, "src", "version.ts");
const PACKAGE_JSON_PATH = path.join(ROOT, "package.json");

function readStateMilestone() {
  if (!fs.existsSync(STATE_PATH)) {
    process.stderr.write(`Error: STATE.md not found at ${STATE_PATH}\n`);
    process.exit(1);
  }

  const content = fs.readFileSync(STATE_PATH, "utf-8");
  const match = content.match(/^milestone:\s*v(\d+\.\d+)/m);

  if (!match) {
    process.stderr.write("Error: Could not parse milestone from STATE.md frontmatter\n");
    process.exit(1);
  }

  return match[1];
}

function buildVersionString(baseVersion) {
  const buildNumber = process.env.BUILD_NUMBER;
  const commitSha = process.env.COMMIT_SHA;

  if (buildNumber && commitSha) {
    const shortSha = commitSha.slice(0, 7);
    return `${baseVersion}+${buildNumber}.${shortSha}`;
  }

  return `${baseVersion}+dev`;
}

function generateVersionTs(versionString) {
  const buildNumber = process.env.BUILD_NUMBER || "dev";
  const gitSha = process.env.COMMIT_SHA ? process.env.COMMIT_SHA.slice(0, 7) : "local";
  const buildDate = new Date().toISOString();

  const content = `/**
 * Docora Version — Generated by scripts/extract-version.cjs
 * Do not edit manually. Run: node scripts/extract-version.cjs
 */
export const VERSION = "${versionString}";

export const BUILD_INFO = {
  version: "${versionString}",
  buildNumber: "${buildNumber}",
  gitSha: "${gitSha}",
  buildDate: "${buildDate}",
} as const;

export type BuildInfo = typeof BUILD_INFO;
`;

  fs.writeFileSync(VERSION_TS_PATH, content);
}

function syncPackageJson(baseVersion) {
  const raw = fs.readFileSync(PACKAGE_JSON_PATH, "utf-8");
  const pkg = JSON.parse(raw);
  pkg.version = `${baseVersion}.0`;
  fs.writeFileSync(PACKAGE_JSON_PATH, JSON.stringify(pkg, null, 2) + "\n");
}

// --- Main ---

const baseVersion = readStateMilestone();
const versionString = buildVersionString(baseVersion);

generateVersionTs(versionString);
syncPackageJson(baseVersion);

process.stdout.write(versionString + "\n");
