/**
 * Docora Version — Generated by scripts/extract-version.cjs
 * Do not edit manually. Run: node scripts/extract-version.cjs
 */
export const VERSION = "1.3+dev";

export const BUILD_INFO = {
  version: "1.0+dev",
  buildNumber: "dev",
  gitSha: "local",
  buildDate: "2026-02-26T08:06:55.800Z",
} as const;

export type BuildInfo = typeof BUILD_INFO;
